-- MySQL Script generated by MySQL Workbench
-- vie 06 nov 2015 11:46:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pintxatordb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pintxatordb` ;

-- -----------------------------------------------------
-- Schema pintxatordb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pintxatordb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pintxatordb` ;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Pincho`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `pintxatordb`.`Usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Usuarios` (
  `loginUsuario` VARCHAR(45) NOT NULL ,
  `passwordUsuario` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
   PRIMARY KEY (`loginUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginUsuario_UNIQUE` ON `pintxatordb`.`Usuarios` (`loginUsuario` ASC);

SHOW WARNINGS;




DROP TABLE IF EXISTS `pintxatordb`.`Pincho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Pincho` (
  `idPincho` INT NOT NULL,
  `nombrePincho` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `celiaco` VARCHAR(2) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `ganadorPopular` VARCHAR(45) NOT NULL,
  `ganadorProfesional` VARCHAR(45) NOT NULL,
  `puntosPopular` INT NOT NULL,
  `mediaPuntosProfesional` INT NOT NULL,
  `contadorVotosPop` INT NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPincho`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPincho_UNIQUE` ON `pintxatordb`.`Pincho` (`idPincho` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Establecimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Establecimiento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Establecimiento` (
  `idEstablecimiento` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cif` VARCHAR(20) NOT NULL,
  `nombreEstablecimiento` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(30) NOT NULL,
  `paginaWeb` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `Pincho_idPincho` INT ,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idEstablecimiento`, `Pincho_idPincho`),
  CONSTRAINT `fk_Establecimiento_Pincho1`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `pintxatordb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idEstablecimiento_UNIQUE` ON `pintxatordb`.`Establecimiento` (`idEstablecimiento` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Establecimiento_Pincho1_idx` ON `pintxatordb`.`Establecimiento` (`Pincho_idPincho` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`JuradoProfesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`JuradoProfesional` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`JuradoProfesional` (
  `idJuradoProfesional` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idJuradoProfesional`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idJuradoProfesional_UNIQUE` ON `pintxatordb`.`JuradoProfesional` (`idJuradoProfesional` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`JuradoPopular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`JuradoPopular` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`JuradoPopular` (
  `idJuradoPopular` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,  
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idJuradoPopular`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `pintxatordb`.`JuradoPopular` (`idJuradoPopular` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `mailAdmin` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idAdministrador_UNIQUE` ON `pintxatordb`.`Administrador` (`idAdministrador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Folleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Folleto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Folleto` (
  `idFolleto` INT NOT NULL,
  `titulo` VARCHAR(25) NOT NULL,
  `descripcion` TEXT(200) NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idFolleto`, `Administrador_idAdministrador`),
  CONSTRAINT `fk_Folleto_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `pintxatordb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idFolleto_UNIQUE` ON `pintxatordb`.`Folleto` (`idFolleto` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Folleto_Administrador1_idx` ON `pintxatordb`.`Folleto` (`Administrador_idAdministrador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Patrocinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Patrocinador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Patrocinador` (
  `idPatrocinador` INT NOT NULL,
  `nombrePatrocinador` VARCHAR(45) NOT NULL,
  `importe` DECIMAL(10,0) NOT NULL,
  `telefonoPatrocinador` INT NOT NULL,
  PRIMARY KEY (`idPatrocinador`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPatrocinador_UNIQUE` ON `pintxatordb`.`Patrocinador` (`idPatrocinador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Premio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Premio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Premio` (
  `idPremio` INT NOT NULL,
  `importePopular` DECIMAL(10,0) NOT NULL,
  `importeProfesional` DECIMAL(10,0) NOT NULL,
  `fechaPremio` DATE NOT NULL,
  `Patrocinador_idPatrocinador` INT NOT NULL,
  PRIMARY KEY (`idPremio`, `Patrocinador_idPatrocinador`),
  CONSTRAINT `fk_Premio_Patrocinador1`
    FOREIGN KEY (`Patrocinador_idPatrocinador`)
    REFERENCES `pintxatordb`.`Patrocinador` (`idPatrocinador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPremio_UNIQUE` ON `pintxatordb`.`Premio` (`idPremio` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Premio_Patrocinador1_idx` ON `pintxatordb`.`Premio` (`Patrocinador_idPatrocinador` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`VotoProfesinal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`VotoProfesinal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`VotoProfesinal` (
  `Pincho_idPincho` INT NOT NULL,
  `JuradoProfesional_idJuradoProfesional` INT NOT NULL,
  `puntuacionMedia` DECIMAL(10,0) NOT NULL,
  `votos5` INT NOT NULL,
  `votos4` INT NOT NULL,
  `votos3` INT NOT NULL,
  `votos2` INT NOT NULL,
  `votos1` INT NOT NULL,
  PRIMARY KEY (`Pincho_idPincho`, `JuradoProfesional_idJuradoProfesional`),
  CONSTRAINT `fk_VotoProfesinal_Pincho`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `pintxatordb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VotoProfesinal_JuradoProfesional1`
    FOREIGN KEY (`JuradoProfesional_idJuradoProfesional`)
    REFERENCES `pintxatordb`.`JuradoProfesional` (`idJuradoProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_VotoProfesinal_Pincho_idx` ON `pintxatordb`.`VotoProfesinal` (`Pincho_idPincho` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_VotoProfesinal_JuradoProfesional1_idx` ON `pintxatordb`.`VotoProfesinal` (`JuradoProfesional_idJuradoProfesional` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Codigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Codigo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Codigo` (
  `idCodigo` INT NOT NULL,
  `codigoVotacion` INT NOT NULL,
  `codigoEstado` TINYINT(1) NULL,
  `Pincho_idPincho` INT NOT NULL,
  PRIMARY KEY (`idCodigo`),
  CONSTRAINT `fk_Codigo_Pincho1`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `pintxatordb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCodigo_UNIQUE` ON `pintxatordb`.`Codigo` (`idCodigo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Codigo_Pincho1_idx` ON `pintxatordb`.`Codigo` (`Pincho_idPincho` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`GastroMapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`GastroMapa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`GastroMapa` (
  `idGastroMapa` INT NOT NULL,
  `coordenadas` DECIMAL(10,0) NOT NULL,
  `Establecimiento_idEstablecimiento` INT NOT NULL,
  `Establecimiento_Pincho_idPincho` INT NOT NULL,
  PRIMARY KEY (`idGastroMapa`, `Establecimiento_idEstablecimiento`, `Establecimiento_Pincho_idPincho`),
  CONSTRAINT `fk_GastroMapa_Establecimiento1`
    FOREIGN KEY (`Establecimiento_idEstablecimiento` , `Establecimiento_Pincho_idPincho`)
    REFERENCES `pintxatordb`.`Establecimiento` (`idEstablecimiento` , `Pincho_idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Las coordenadas las mete el administrador pero lo que importa es que se relacionen las coordenadas con el establecimiento\n';

SHOW WARNINGS;
CREATE UNIQUE INDEX `idGastroMapa_UNIQUE` ON `pintxatordb`.`GastroMapa` (`idGastroMapa` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_GastroMapa_Establecimiento1_idx` ON `pintxatordb`.`GastroMapa` (`Establecimiento_idEstablecimiento` ASC, `Establecimiento_Pincho_idPincho` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Premio_pincho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`Premio_pincho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`Premio_pincho` (
  `Pincho_idPincho` INT NOT NULL,
  `Premio_idPremio` INT NOT NULL,
  PRIMARY KEY (`Pincho_idPincho`, `Premio_idPremio`),
  CONSTRAINT `fk_Premio_pincho_Pincho1`
    FOREIGN KEY (`Pincho_idPincho`)
    REFERENCES `pintxatordb`.`Pincho` (`idPincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Premio_pincho_Premio1`
    FOREIGN KEY (`Premio_idPremio`)
    REFERENCES `pintxatordb`.`Premio` (`idPremio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Premio_pincho_Premio1_idx` ON `pintxatordb`.`Premio_pincho` (`Premio_idPremio` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pintxatordb`.`Usuarios`
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `pintxatordb`.`VotoPopular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pintxatordb`.`VotoPopular` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pintxatordb`.`VotoPopular` (
  `contadorVotosPop` INT NOT NULL,
  `idJuradoPopular` INT NOT NULL,
  `idCodigo` INT NOT NULL,
  PRIMARY KEY (`idJuradoPopular`, `idCodigo`),
  CONSTRAINT `fk_VotoPopular_1`
    FOREIGN KEY (`idJuradoPopular`)
    REFERENCES `pintxatordb`.`JuradoPopular` (`idJuradoPopular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VotoPopular_2`
    FOREIGN KEY (`idCodigo`)
    REFERENCES `pintxatordb`.`Codigo` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_VotoPopular_2_idx` ON `pintxatordb`.`VotoPopular` (`idCodigo` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `JuradoPopular`(`idJuradoPopular`, `login`, `password`, `dni`, `nombre`, `apellidos`, `mail`, `telefono`, `tipo`) VALUES 
(211111111,"mcpaz","mcpaz","121223242","mcpaz","mcpaz","mcpaz",988272666,"Jurado popular");

INSERT INTO `JuradoPopular`(`idJuradoPopular`, `login`, `password`, `dni`, `nombre`, `apellidos`, `mail`, `telefono`, `tipo`) VALUES 
(222222222,"jesus","jesus","121223242","jesus","jesus","jesus",988272666,"Jurado popular");


INSERT INTO `Pincho`(`idPincho`, `nombrePincho`, `descripcion`, `precio`, `celiaco`, `estado`, `ganadorPopular`, `ganadorProfesional`, `puntosPopular`, `mediaPuntosProfesional`, `contadorVotosPop`, `imagen`) VALUES
 (111111111,"pinchoRestaurante","pincho rico",2,"si",1,"no pillo esto","no pillo esto",12,13,12,"img/10.jpg");

 INSERT INTO `Pincho`(`idPincho`, `nombrePincho`, `descripcion`, `precio`, `celiaco`, `estado`, `ganadorPopular`, `ganadorProfesional`, `puntosPopular`, `mediaPuntosProfesional`, `contadorVotosPop`, `imagen`) VALUES
 (222222222,"pinchoBar","pincho podre",2,"si",1,"no pillo esto","no pillo esto",12,13,12,"img/11.jpg");

 INSERT INTO `Pincho`(`idPincho`, `nombrePincho`, `descripcion`, `precio`, `celiaco`, `estado`, `ganadorPopular`, `ganadorProfesional`, `puntosPopular`, `mediaPuntosProfesional`, `contadorVotosPop`, `imagen`) VALUES
 (333333333,"pinchoMeson","pincho bah",2,"si",1,"no pillo esto","no pillo esto",12,13,12,"img/12.jpg");



 INSERT INTO `Pincho`(`idPincho`, `nombrePincho`, `descripcion`, `precio`, `celiaco`, `estado`, `ganadorPopular`, `ganadorProfesional`, `puntosPopular`, `mediaPuntosProfesional`, `contadorVotosPop`, `imagen`) VALUES
 (444444444,"pincho de mierda","pincho bah",2,"si",1,"no pillo esto","no pillo esto",12,13,12,"img/14.jpg");



INSERT INTO `Establecimiento`(`idEstablecimiento`, `login`, `password`, `cif`, `nombreEstablecimiento`, `direccion`, `horario`, `paginaWeb`, `telefono`, `Pincho_idPincho`, `tipo`) 
VALUES (111111111,"restaurante","restaurante","1111111111","restaurante","aki","10.00-20:00","restaurante.com",988271111,111111111,"Establecimiento");

INSERT INTO `Establecimiento`(`idEstablecimiento`, `login`, `password`, `cif`, `nombreEstablecimiento`, `direccion`, `horario`, `paginaWeb`, `telefono`, `Pincho_idPincho`, `tipo`) 
VALUES (122222222,"bar","bar","1111111111","bar","alla","10.00-20:00","bar.com",988272222,222222222,"Establecimiento");

INSERT INTO `Establecimiento`(`idEstablecimiento`, `login`, `password`, `cif`, `nombreEstablecimiento`, `direccion`, `horario`, `paginaWeb`, `telefono`, `Pincho_idPincho`, `tipo`) 
VALUES (133333333,"meson","meson","1111111111","meson","por alla","10.00-20:00","meson.com",988273333,333333333,"Establecimiento");